/**
 * Supplement Facts data — ported verbatim from the Claude Design source
 * `product-facts.js` (window.ORGANICA_FACTS) imported via the claude_design MCP.
 * This is the authoritative label data for the Product detail page.
 *
 * Row shape mirrors the mockup: n = nutrient name, a = amount per serving, dv = % DV.
 */
export type FactRow = { n: string; a: string; dv: string };
export type FactWarning = { t: string; d: string };
export type ProductFacts = {
  serving: string;
  servings: string;
  rows: FactRow[];
  ingredients: string;
  warnings: FactWarning[];
};

export const ORGANICA_FACTS: Record<string, ProductFacts> = {
  "multi-pro": {
    serving: "2 Capsule",
    servings: "30",
    rows: [
      { n: "Vitamin A", a: "1050 mcg", dv: "132%" },
      { n: "Pantothenic Acid", a: "10 mg", dv: "167%" },
      { n: "Vitamin D3", a: "10 mcg", dv: "200%" },
      { n: "Magnesium Glycinate", a: "100 mg", dv: "100%" },
      { n: "Vitamin E", a: "20 mg", dv: "167%" },
      { n: "Iron", a: "18 mg", dv: "129%" },
      { n: "Vitamin K2", a: "25 mcg", dv: "33%" },
      { n: "Zinc Gluconate", a: "15 mg", dv: "150%" },
      { n: "Vitamin C", a: "80 mg", dv: "100%" },
      { n: "Copper", a: "1.5 mg", dv: "150%" },
      { n: "Vitamin B1", a: "1.5 mg", dv: "136%" },
      { n: "Selenium", a: "55 mcg", dv: "100%" },
      { n: "Vitamin B2", a: "1.4 mg", dv: "105%" },
      { n: "Iodine", a: "150 mcg", dv: "129%" },
      { n: "Vitamin B3", a: "18 mg", dv: "112%" },
      { n: "Chromium", a: "50 mcg", dv: "125%" },
      { n: "Vitamin B6", a: "2 mg", dv: "143%" },
      { n: "Molybdenum", a: "50 mcg", dv: "77%" },
      { n: "Vitamin B12", a: "6 mcg", dv: "240%" },
      { n: "Phosphorous", a: "109 mg", dv: "16%" },
      { n: "Biotin", a: "50 mcg", dv: "100%" },
      { n: "Boron", a: "2 mg", dv: "—" },
      { n: "Folic Acid", a: "400 mcg", dv: "200%" },
      { n: "Omega-3 DHA", a: "63 mg", dv: "—" },
      { n: "Calcium Citrate", a: "160 mg", dv: "20%" },
      { n: "Omega-3 EPA", a: "102 mg", dv: "—" },
      { n: "Potassium", a: "80 mg", dv: "4%" },
      { n: "Lutein", a: "200 mcg", dv: "—" },
      { n: "Chloride", a: "72 mg", dv: "9%" },
      { n: "Lycopene", a: "300 mcg", dv: "—" },
      { n: "Manganese", a: "2 mg", dv: "100%" },
      { n: "Coenzyme Q10", a: "100 mg", dv: "—" },
    ],
    ingredients:
      "Tapioca Syrup, Cane Sugar, Water, Gelling Agent (Pectin), Acidity Regulators (Malic Acid, Citric Acid, Sodium Citrate), Vitamin C (as Ascorbic Acid), Natural Flavourings, Sweet Potato Juice Concentrate, Carrot Juice Concentrate, Vitamin E (as dl-Alpha Tocopheryl Acetate), Niacinamide, Zinc (as Zinc Citrate), Pantothenic Acid, Vitamin A (as Retinyl Palmitate), Pyridoxine HCl (Vitamin B6), Riboflavin, Thiamin, Manganese (as Manganese Sulphate), Biotin, Folate (as Folic Acid), Vitamin D3 (as Ergocalciferol), Vitamin K2 (as Menaquinone), Copper (as Copper Gluconate), Selenium (as Sodium Selenite), Chromium (as Chromium Chloride), Vitamin B12 (as Cyanocobalamin).",
    warnings: [
      {
        t: "WARNING",
        d: "Accidental overdose of iron-containing products is a leading cause of fatal poisoning in children under 6. Keep this product out of reach of children. In case of accidental overdose, call a doctor or poison control center immediately.",
      },
    ],
  },
  "optimus-d3": {
    serving: "1 Softgel",
    servings: "30",
    rows: [{ n: "Vitamin D3 (Cholecalciferol)", a: "125 mcg (5000 IU)", dv: "2500%" }],
    ingredients: "",
    warnings: [
      {
        t: "WARNING",
        d: "Consult a healthcare professional prior to use if pregnant, breastfeeding, taking any medications (especially blood thinners/anticoagulants) or have any medical conditions. Do not exceed stated dose. Keep out of reach of children. Do not use if safety seal is damaged or missing.",
      },
    ],
  },
  "optimus-d3-mini": {
    serving: "1 Gummy",
    servings: "30",
    rows: [
      { n: "Vitamin D3 (Cholecalciferol)", a: "10 mcg", dv: "200%" },
      { n: "Magnesium Glycinate", a: "100 mg", dv: "27%" },
      { n: "Calcium Citrate", a: "350 mg", dv: "44%" },
      { n: "Zinc Gluconate", a: "5 mg", dv: "50%" },
      { n: "Phosphorus", a: "180 mg", dv: "26%" },
      { n: "Boron", a: "0.5 mg", dv: "—" },
      { n: "Vitamin K2", a: "60 mg", dv: "80%" },
      { n: "Omega-3 (Fish Oil)", a: "582 mg", dv: "—" },
      { n: "Vitamin C", a: "50 mg", dv: "62%" },
    ],
    ingredients:
      "Tapioca Syrup, Cane Sugar, Water, Gelling Agent (Pectin), Acidity Regulators (Malic Acid, Citric Acid, Sodium Citrate), Vitamin C (as Ascorbic Acid), Natural Flavourings, Sweet Potato Juice Concentrate, Zinc (as Gluconate), Pantothenic Acid, Vitamin A (as Retinyl Palmitate), Manganese (as Manganese Sulphate).",
    warnings: [
      {
        t: "WARNING",
        d: "Consult a healthcare professional prior to use if the child is taking any medications (especially blood thinners/anticoagulants) or has a medical condition. Do not exceed stated dose. Do not use if safety seal is damaged or missing.",
      },
      {
        t: "Choking Hazard",
        d: "Not recommended for children under 3 years of age; requires adult supervision.",
      },
      { t: "Allergen Warning", d: "Contains Fish (Source of Omega-3)." },
    ],
  },
  "omega-1000": {
    serving: "1 Softgel",
    servings: "60",
    rows: [
      { n: "Omega-3", a: "1000 mg", dv: "—" },
      { n: "Vitamin E (D-alpha tocopherol)", a: "134 mg", dv: "1000%" },
      { n: "EPA 520 mg", a: "520 mg", dv: "—" },
      { n: "DHA: 330mg", a: "330 mg", dv: "—" },
    ],
    ingredients: "",
    warnings: [
      {
        t: "WARNING",
        d: "Consult a healthcare professional prior to use if you are pregnant, breastfeeding, taking blood thinners (anticoagulants), or have a medical condition. Do not exceed stated dose. Keep out of reach of children. Do not use if safety seal is damaged or missing.",
      },
      {
        t: "Allergen Warning",
        d: "Contains Fish (Salmon, Sardines, Anchovies, Mackerel, Tuna, Herring, or Cod).",
      },
    ],
  },
  "vision-pro": {
    serving: "2 Softgels",
    servings: "15",
    rows: [
      { n: "Vitamin A", a: "300 mcg", dv: "38%" },
      { n: "Chromium", a: "50 mcg", dv: "125%" },
      { n: "Vitamin D3", a: "5 mcg", dv: "100%" },
      { n: "Iodine", a: "100 mcg", dv: "67%" },
      { n: "Vitamin E", a: "80 mg", dv: "665%" },
      { n: "Zinc", a: "30 mg", dv: "300%" },
      { n: "Vitamin C", a: "250 mg", dv: "312%" },
      { n: "Lutein", a: "20 mg", dv: "—" },
      { n: "Vitamin B1", a: "12 mg", dv: "1088%" },
      { n: "Zeaxanthin", a: "4 mg", dv: "—" },
      { n: "Vitamin B2", a: "4.8 mg", dv: "360%" },
      { n: "Natural Carotenoids", a: "3 mg", dv: "—" },
      { n: "Vitamin B3", a: "18 mg", dv: "112%" },
      { n: "Sunflower & Safflower Seed", a: "150 mcg", dv: "—" },
      { n: "Vitamin B6", a: "10 mg", dv: "715%" },
      { n: "Phosphatidylserine,", a: "", dv: "—" },
      { n: "Vitamin B12", a: "12 mcg", dv: "480%" },
      { n: "Phosphatidylcholine, and", a: "", dv: "—" },
      { n: "Folic Acid", a: "400 mcg", dv: "200%" },
      { n: "Sphingomyelin", a: "80 mg", dv: "—" },
      { n: "Pantothenic Acid", a: "20 mcg", dv: "334%" },
      { n: "Citrus Bioflavonoids", a: "15 mg", dv: "—" },
      { n: "Magnesium", a: "60 mcg", dv: "16%" },
      { n: "Ribes Nigrum & Bilberry Exts", a: "50 mcg", dv: "—" },
      { n: "Iron", a: "8 mg", dv: "57%" },
      { n: "Hippophae Rhamnoides Exts", a: "50 mcg", dv: "—" },
      { n: "Copper", a: "1000 mcg", dv: "100%" },
      { n: "Omega-7 (Palmitoleic Acid)", a: "109 mg", dv: "—" },
      { n: "Manganese", a: "2 mg", dv: "100%" },
      { n: "Omega-3 (EPA:102 DHA:63mg)", a: "165 mcg", dv: "—" },
      { n: "Selenium", a: "100 mcg", dv: "182%" },
      { n: "Coenzyme Q10", a: "100 mg", dv: "—" },
    ],
    ingredients: "",
    warnings: [
      {
        t: "WARNING",
        d: "Do not exceed the recommended dose. Pregnant or nursing mothers, children under the age of 18, and individuals with a known medical condition should consult a physician before using this or any dietary supplement.",
      },
      {
        t: "IRON WARNING (CRITICAL)",
        d: '"Accidental overdose of iron-containing products is a leading cause of fatal poisoning in children under 6. Keep this product out of reach of children. In case of accidental overdose, call a doctor or poison control center immediately." (Contains 8mg Iron per serving)',
      },
      {
        t: "ZINC INTAKE",
        d: '"Contains 30mg of Zinc. Long-term intake of high levels of zinc can inhibit copper absorption. This formula includes 1mg of Copper to mitigate this risk, but consult a doctor if taking other zinc supplements."',
      },
    ],
  },
  "sleep-pro": {
    serving: "1 Gummy",
    servings: "30",
    rows: [
      { n: "Melatonin", a: "5 mg", dv: "—" },
      { n: "Vitamin B6 (Pyridoxine)", a: "50 mg", dv: "3575%" },
      { n: "5-HTP (5-Hydroxytryptophan)", a: "30 mg", dv: "—" },
      { n: "Vitamin B9 (Folate)", a: "400 mcg", dv: "200%" },
      { n: "L-Theanine", a: "30 mg", dv: "—" },
      { n: "Vitamin B12 (Methylcobalamin)", a: "80 mcg", dv: "3333%" },
      { n: "GABA (Gamma-Aminobutyric Acid)", a: "100 mg", dv: "125%" },
      { n: "Magnesium Glycinate", a: "10 mg", dv: "124%" },
      { n: "Ashwagandha Extracts", a: "100 mg", dv: "—" },
      { n: "Valerian Root Extracts", a: "200 mg", dv: "—" },
      { n: "Chamomile Extracts", a: "100 mg", dv: "—" },
      { n: "Rhodiola Rosea Extracts", a: "250 mg", dv: "—" },
    ],
    ingredients: "",
    warnings: [
      {
        t: "WARNING",
        d: "Do not exceed the recommended dose. Pregnant or nursing mothers, children under the age of 18, and individuals with a known medical condition should consult a physician before using this or any dietary supplement.",
      },
      {
        t: "DRIVING WARNING",
        d: "Do not drive or operate heavy machinery within 8 hours of taking this product.",
      },
      {
        t: "MEDICATION INTERACTION",
        d: "If you are taking antidepressants, sedatives, or sleep medications, consult your healthcare provider before use to avoid potential interactions with 5-HTP and GABA.",
      },
    ],
  },
  "glow-pro": {
    serving: "2 Gummies",
    servings: "15",
    rows: [
      { n: "Biotin", a: "10,000 mcg", dv: "18180%" },
      { n: "Calcium (Tricalcium Phosphate)", a: "80 mg", dv: "10%" },
      { n: "Vitamin A (Retinyl Palmitate)", a: "1,200 mcg", dv: "151%" },
      { n: "Phosphorus", a: "40 mg", dv: "6%" },
      { n: "Vitamin D3 (Cholecalciferol)", a: "15 mcg", dv: "300%" },
      { n: "Zinc (Zinc Picolinate)", a: "15 mg", dv: "150%" },
      { n: "Vitamin C (Ascorbic Acid)", a: "100 mg", dv: "125%" },
      { n: "Selenium (Selenomethionine)", a: "30 mcg", dv: "55%" },
      { n: "Vitamin E (D-alpha Tocopherol)", a: "15 mg", dv: "124%" },
      { n: "Copper (Gluconate)", a: "1 mg", dv: "100%" },
      { n: "Vitamin K2", a: "100 mg", dv: "133%" },
      { n: "Manganese", a: "1.5 mg", dv: "75%" },
      { n: "Vitamin B1 (Thiamin HCl)", a: "5 mg", dv: "453%" },
      { n: "Astaxanthin", a: "4 mcg", dv: "—" },
      { n: "Vitamin B2 (Riboflavin)", a: "5 mg", dv: "3755%" },
      { n: "Collagen Peptides Types I-III", a: "100 mg", dv: "—" },
      { n: "Vitamin B3 (Niacinamide)", a: "5 mg", dv: "31%" },
      { n: "Hyaluronic Acid", a: "3 mg", dv: "—" },
      { n: "Vitamin B6 (Pyridoxine HCl)", a: "5 mg", dv: "357%" },
      { n: "Glutathione Reduced", a: "100 mg", dv: "—" },
      { n: "Folate (Folic Acid 200 mcg)", a: "340 mcg", dv: "100%" },
      { n: "L-Cysteine (NAC)", a: "100 mg", dv: "—" },
      { n: "Vitamin B12 (Methylcobalamin)", a: "20 mcg", dv: "800%" },
      { n: "Coenzyme Q10 (Ubiquinol)", a: "100 mg", dv: "—" },
      { n: "Pantothenic Acid", a: "50 mg", dv: "835%" },
    ],
    ingredients:
      "Proprietary Blend: 500 mg containing Green Tea Extracts 20:1, Aloe Vera Extracts 100:1, Methylsulfonylmethane (MSM), Hydrolyzed Keratin, Bamboo Extracts (Bambusa vulgaris) (Stem & Leaf) (std. to 70% silica), Horsetail Extracts 10:1, Coconut Oil, Nettle Extracts (Root), Grape Seed Extracts 20:1 (Vitis Vinifera), Organic Rice Flour.",
    warnings: [
      {
        t: "WARNING",
        d: "Do not exceed the recommended dose. Pregnant or nursing mothers, children under the age of 18, and individuals with a known medical condition should consult a physician before using this or any dietary supplement.",
      },
      {
        t: "BIOTIN NOTICE",
        d: "This product contains 10,000mcg of Biotin. Biotin may interfere with certain laboratory tests (including thyroid and troponin). Inform your healthcare provider that you are taking this supplement prior to any blood work.",
      },
      {
        t: "VITAMIN A",
        d: "This product contains Vitamin A (Retinyl Palmitate). If you are pregnant or likely to become pregnant, or are taking other retinoid products, consult your doctor.",
      },
      {
        t: "ALLERGEN WARNING",
        d: "Contains Coconut Oil and potentially Fish/Shellfish (depending on the source of the Hydrolyzed Keratin and Collagen Peptides).",
      },
    ],
  },
  bloom: {
    serving: "1 Gummy",
    servings: "30",
    rows: [
      { n: "Folic Acid", a: "500 mcg", dv: "250%" },
      { n: "Pantothenic Acid", a: "6 mg", dv: "100%" },
      { n: "Vitamin D3", a: "10 mcg", dv: "200%" },
      { n: "Magnesium Glycinate", a: "150 mg", dv: "40%" },
      { n: "Vitamin E", a: "20 mg", dv: "167%" },
      { n: "Iron", a: "25 mg", dv: "178%" },
      { n: "Vitamin K1", a: "75 mcg", dv: "100%" },
      { n: "Zinc", a: "15 mg", dv: "150%" },
      { n: "Vitamin C", a: "80 mg", dv: "100%" },
      { n: "Copper", a: "1 mg", dv: "100%" },
      { n: "Vitamin B1", a: "3 mg", dv: "272%" },
      { n: "Selenium", a: "55 mcg", dv: "100%" },
      { n: "Vitamin B2", a: "2 mg", dv: "150%" },
      { n: "Inositol", a: "10 mcg", dv: "—" },
      { n: "Vitamin B3", a: "16 mg", dv: "100%" },
      { n: "Beta-Carotene", a: "2 mg", dv: "—" },
      { n: "Vitamin B6", a: "10 mg", dv: "714%" },
      { n: "Omega-3 DHA", a: "260 mg", dv: "—" },
      { n: "Vitamin B12", a: "12 mcg", dv: "480%" },
      { n: "Omega-3 EPA", a: "100 mg", dv: "—" },
      { n: "Biotin", a: "150 mcg", dv: "300%" },
      { n: "Choline", a: "10 mg", dv: "—" },
      { n: "Iodine", a: "150 mg", dv: "100%" },
      { n: "Lutein", a: "3 mg", dv: "—" },
      { n: "Calcium Malate", a: "150 mg", dv: "19%" },
      { n: "Coenzyme Q10", a: "100 mg", dv: "—" },
    ],
    ingredients:
      "Tapioca Syrup, Cane Sugar, Water, Gelling Agent (Pectin), Acidity Regulators (Malic Acid, Citric Acid, Sodium Citrate), Vitamin C (as Ascorbic Acid), Natural Flavourings, Sweet Potato Juice Concentrate, Carrot Juice Concentrate, Vitamin E (as dl-Alpha Tocopheryl Acetate), Niacinamide, Zinc (as Zinc Citrate), Pantothenic Acid, Vitamin A (as Retinyl Palmitate), Pyridoxine HCl (Vitamin B6), Riboflavin, Thiamin, Manganese (as Manganese Sulphate), Biotin, Folate (as Folic Acid), Vitamin D2 (as Ergocalciferol), Vitamin K1 (as Phytomenadione), Copper (as Copper Gluconate), Selenium (as Sodium Selenite), Chromium (as Chromium Chloride), Vitamin B12 (as Cyanocobalamin).",
    warnings: [
      {
        t: "WARNING",
        d: "Accidental overdose of iron-containing products is a leading cause of fatal poisoning in children under 6. Keep this product out of reach of children. In case of accidental overdose, call a doctor or poison control center immediately. Consult a healthcare professional prior to use if taking blood thinners (anticoagulants) or other medications. Do not use if safety seal is damaged.",
      },
    ],
  },
  "meno-pro": {
    serving: "2 Capsules",
    servings: "15",
    rows: [
      { n: "Vitamin A", a: "750 mcg", dv: "94%" },
      { n: "Biotin", a: "30 mcg", dv: "60%" },
      { n: "Vitamin C", a: "60 mg", dv: "75%" },
      { n: "Pantothenic Acid", a: "10 mg", dv: "167%" },
      { n: "Vitamin D3", a: "10 mcg", dv: "200%" },
      { n: "Magnesium", a: "100 mg", dv: "27%" },
      { n: "Vitamin B1", a: "10 mg", dv: "906%" },
      { n: "Iron", a: "8 mg", dv: "57%" },
      { n: "Vitamin B2", a: "5 mg", dv: "375%" },
      { n: "Zinc", a: "20 mg", dv: "200%" },
      { n: "Vitamin B3", a: "20 mg", dv: "124%" },
      { n: "Copper", a: "1000 mcg", dv: "100%" },
      { n: "Vitamin B6", a: "10 mg", dv: "714%" },
      { n: "Manganese", a: "1 mg", dv: "50%" },
      { n: "Vitamin B12", a: "10 mcg", dv: "400%" },
      { n: "Selenium", a: "100 mcg", dv: "182%" },
      { n: "Vitamin E", a: "30 mg", dv: "250%" },
      { n: "Chromium", a: "50 mcg", dv: "125%" },
      { n: "Folic Acid", a: "400 mcg", dv: "200%" },
      { n: "Iodine", a: "225 mcg", dv: "150%" },
      { n: "Omega 3 (EPA)", a: "65 mg", dv: "—" },
      { n: "L-Theanine", a: "50 mg", dv: "—" },
      { n: "Melatonin", a: "2 mg", dv: "—" },
      { n: "Bacillus Subtilis (260 mil CFUs)", a: "150 mg", dv: "—" },
      { n: "Ashwagandha Root Extracts", a: "100 mg", dv: "—" },
      { n: "Dong Quai Extracts", a: "35 mg", dv: "—" },
      { n: "Wild Yam Extract", a: "50 mg", dv: "—" },
      { n: "Moringa Leaf Extracts", a: "100 mcg", dv: "—" },
      { n: "Kerria Japonica Extracts", a: "150 mg", dv: "—" },
      { n: "Soya Isoflavone Extracts (Equol)", a: "20 mg", dv: "—" },
    ],
    ingredients: "",
    warnings: [
      {
        t: "WARNING",
        d: "Do not exceed the recommended dose (2 Capsules). Pregnant or nursing mothers, children under 18, and individuals with a known medical condition should consult a physician before using.",
      },
      {
        t: "SPECIFIC ALERTS",
        d: "Drowsiness: May cause drowsiness (Melatonin). Allergens: Contains Soy and Iron.",
      },
    ],
  },
};
